In [1]:
import pandas as pd
import matplotlib as mpl
import matplotlib.pyplot as plt

import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Activation
from keras.models import model_from_json
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, StandardScaler
from sklearn import metrics

In [2]:
df =pd.read_csv("Engine.csv")

In [3]:
df.drop('time', axis=1, inplace=True)

In [4]:
df.describe()

1011001      1011002      1011003      1011004      1011005  \
count  3193.000000  3193.000000  3193.000000  3193.000000  3193.000000   
mean    267.043422   269.177611   267.043422   267.310197   267.576976   
std       2.324810     2.343388     2.324810     2.327131     2.329455   
min     266.592102   268.722687   266.592102   266.858429   267.124756   
25%     266.592102   268.722687   266.592102   266.858429   267.124756   
50%     266.592102   268.722687   266.592102   266.858429   267.124756   
75%     266.592102   268.722687   266.592102   266.858429   267.124756   
max     288.999207   291.308838   288.999207   289.287872   289.576599   

           1011006      1011007      1011008      1011009      1011010  ...  \
count  3193.000000  3193.000000  3193.000000  3193.000000  3193.000000  ...   
mean    267.310197   267.310197   267.043422   349.067071   266.776643  ...   
std       2.327131     2.327131     2.324810     3.705434     2.322490  ...   
min     266.858429   266.858429   266.592102   348.369965   266.325775  ...   
25%     266.858429   266.858429   266.592102   348.369965   266.325775  ...   
50%     266.858429   266.858429   266.592102   348.369965   266.325775  ...   
75%     266.858429   266.858429   266.592102   348.369965   266.325775  ...   
max     289.287872   289.287872   288.999207   386.950500   288.710449  ...   

       1011264      1011265      1011266      1011267      1011270  \
count   3193.0  3193.000000  3193.000000  3193.000000  3193.000000   
mean       0.0   267.476924    53.423997    60.410993   512.149910   
std        0.0     2.328585     0.228501     0.014453     0.130367   
min        0.0   267.024872    53.089447    60.408234   512.126038   
25%        0.0   267.024872    53.408504    60.408302   512.126038   
50%        0.0   267.024872    53.409683    60.408318   512.126038   
75%        0.0   267.024872    53.409683    60.408333   512.126038   
max        0.0   289.468323    56.966232    60.549686   513.524719   

            1011271      1011272  1011273      1011466      1011467  
count   3193.000000  3193.000000   3193.0  3193.000000  3193.000000  
mean   13330.702912     0.000140     60.0    40.342769    34.136188  
std       88.623238     0.000317      0.0     0.632620     0.535294  
min    13314.745120     0.000000     60.0    40.227703    34.038826  
25%    13314.765630     0.000000     60.0    40.227795    34.038902  
50%    13314.776370     0.000000     60.0    40.227795    34.038902  
75%    13314.776370     0.000000     60.0    40.227833    34.038937  
max    14336.606450     0.001156     60.0    47.330677    40.049034  

[8 rows x 66 columns]

In [5]:
train_data, test_data = train_test_split(df.values,test_size =0.2, random_state =0)

In [6]:
train_data.shape, test_data.shape

((2554, 66), (639, 66))

In [7]:
model = Sequential()
model.add(Dense(16,input_dim=train_data.shape[1],activation='relu'))
model.add(Dense(4,activation = 'relu'))
model.add(Dense(16,activation = 'relu'))
model.add(Dense(train_data.shape[1]))# Multiple output neurons
model.summary()
model.compile(loss='mean_squared_error',optimizer='adam')
model.fit(train_data,train_data,verbose=1,epochs=100,batch_size=32, validation_split=0.10)


Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 16)                1072      
_________________________________________________________________
dense_1 (Dense)              (None, 4)                 68        
_________________________________________________________________
dense_2 (Dense)              (None, 16)                80        
_________________________________________________________________
dense_3 (Dense)              (None, 66)                1122      
Total params: 2,342
Trainable params: 2,342
Non-trainable params: 0
_________________________________________________________________
Epoch 1/100
72/72 [==============================] - 1s 8ms/step - loss: 2664392.5000 - val_loss: 2421873.7500
Epoch 2/100
72/72 [==============================] - 0s 6ms/step - loss: 1398834.6250 - val_loss: 228710.5000
Epoch 3/100
72/72 [============

72/72 [==============================] - 0s 3ms/step - loss: 5.2466 - val_loss: 2.5446
Epoch 74/100
72/72 [==============================] - 0s 3ms/step - loss: 3.7163 - val_loss: 3.7228
Epoch 75/100
72/72 [==============================] - 0s 3ms/step - loss: 3.3622 - val_loss: 5.8204
Epoch 76/100
72/72 [==============================] - 0s 3ms/step - loss: 3.7443 - val_loss: 5.3383
Epoch 77/100
72/72 [==============================] - 0s 3ms/step - loss: 3.3157 - val_loss: 4.1624
Epoch 78/100
72/72 [==============================] - 0s 4ms/step - loss: 3.8131 - val_loss: 3.7846
Epoch 79/100
72/72 [==============================] - 0s 3ms/step - loss: 3.5714 - val_loss: 3.2990
Epoch 80/100
72/72 [==============================] - 0s 3ms/step - loss: 4.5567 - val_loss: 5.0090
Epoch 81/100
72/72 [==============================] - 0s 3ms/step - loss: 4.4282 - val_loss: 5.8275
Epoch 82/100
72/72 [==============================] - 0s 3ms/step - loss: 3.5214 - val_loss: 3.9539
Epoch 83/100


In [8]:
resconstructions = model.predict(train_data)
score1 = np.sqrt(metrics.mean_squared_error(resconstructions,train_data))
print(score1)

2.447255579337788


In [9]:
train_loss = tf.keras.losses.mae(resconstructions,train_data)
np.mean(train_loss)

2.013916567274072

In [10]:
np.std(train_loss)

0.3704800540527353

In [11]:
threshold = np.mean(train_loss) + 3*np.std(train_loss)
threshold

3.125356729432278

# Inference

In [12]:
train_data, test_data = train_test_split(df.values,test_size =0.1, random_state =111)
anomaly_data = train_data[0]

# anomaly_data[[0]] = 58

In [13]:
resconstructions_inf  = model.predict(anomaly_data.reshape(1,66))
anomaly_loss_inf = tf.keras.losses.mae(resconstructions_inf,anomaly_data)
print(anomaly_loss_inf)

tf.Tensor([1.86668611], shape=(1,), dtype=float64)


In [14]:
score2 = np.sqrt(metrics.mean_squared_error(resconstructions_inf,anomaly_data.reshape(1,66)))
print(score2)

2.128580880874031


In [15]:
anomaly_loss_inf[0],threshold

(<tf.Tensor: shape=(), dtype=float64, numpy=1.866686113742795>,
 3.125356729432278)

In [16]:
inference_res = tf.math.less(anomaly_loss_inf[0],threshold)
print(inference_res)
if inference_res:
    print("Normal ")
else:
    print("Anomaly Detected")

tf.Tensor(True, shape=(), dtype=bool)
Normal 


## Save the model

In [17]:
# serialize model to JSON
model_json = model.to_json()
with open("model.json", "w") as json_file:
    json_file.write(model_json)
# serialize weights to HDF5
model.save_weights("model.h5")
print("Saved model to disk")

Saved model to disk


In [18]:
# load json and create model
json_file = open('model.json', 'r')
loaded_model_json = json_file.read()
json_file.close()
loaded_model = model_from_json(loaded_model_json)
# load weights into new model
loaded_model.load_weights("model.h5")
print("Loaded model from disk")

Loaded model from disk


In [19]:
resconstructions_inf1  = loaded_model.predict(anomaly_data.reshape(1,66))

anomaly_loss_inf1 = tf.keras.losses.mae(resconstructions_inf1,anomaly_data)
print(anomaly_loss_inf1)

tf.Tensor([1.86668611], shape=(1,), dtype=float64)


In [20]:
import pickle

data = { "threshold":threshold}

with open("threshold_value", 'wb') as f:
    pickle.dump(data, f)



In [21]:
with open("threshold_value", 'rb') as f:
    data = pickle.load(f)
print(data['threshold'])

3.125356729432278
